### PR TITLE
Add a PHP 5.3 safety patch for ReactPHP Promise

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Whoop, whoop!

**Comment by bobdenotter** [comment]
thinking about this.. For 2.1.x i use an old version of the packager, because the files that need to be removed have changed a lot.. I think we need to backport this to the version i'm using, and make a branch for it.

**Comment by GawainLynch** [comment]
I have post dinner tired happening, but for 2.1 this one isn't relevant... As these changes are introduced in 2.2-dev... I do need sleep so excuse we potential derp

**Comment by bobdenotter** [comment]
I had a bit of derpyness too, i guess. I assumed it would be relevant for 2.1.x, but i now get that it isn't.. Thanks! :-)

**Pull request merged**
